### PR TITLE
change naming convention

### PR DESCRIPTION
**Pull request by zapplecat**
minor change but someone should review the modules since I merged a bit prematurely.

### CODE REVIEW

**Comment by Mester** [comment]
What exactly did you change that wasn't in the other PR?

**Comment by corez92** [comment]
It's highlighted green and red right lol

aka

random -> gif_random
blah blah

**Comment by Mester** [comment]
He mentioned accidentally mixing/merging branches so some changes went in unnoticed (as you can see by this module not existing in your own branch), not just those two name changes, that's why I asked.

**Comment by zapplecat** [comment]
The other changes are the changes in the PR from #30 

Basically, the previous PR is #30 + #32

**Pull request merged**
