### PR TITLE
added origin user to model and recreate migrations

### PR DESCRIPTION
**Pull request by zapplecat**

### CODE REVIEW

**Comment by Mester** [comment]
Merge master in to this and then fix this error and we can pull it in:
screenshot_2016-08-26_12-34-06

**Comment by Mester** [comment]
Actually I merged it already, just fix the error and make the migrations, then we'll pull it in.

Reopen the PR after

**Comment by zapplecat** [comment]
Fixed errors, please check it over and merge.

**Comment by Mester** [comment]
Looks fine to me

**Pull request merged**
