### PR TITLE
Aesthetics

### PR DESCRIPTION
**Pull request by zapplecat**

### CODE REVIEW

**Comment by corez92** [comment]
Can we receive pics?

**Comment by zapplecat** [comment]
What do you mean?

**Comment by zapplecat** [comment]
Oh, of what I changed? Yeah, let me take screenshots tomorrow. Been a long day today. Everything is pretty minor.

**Comment by zapplecat** [comment]
index

multi game lobby

gameover multi

**Comment by zapplecat** [comment]
Rest is cleaning up code, adding in accepted domain, gitignore for local.py (`DEBUG=True`)

**Pull request merged**
